---
- name: Install Docker and Zabbix agent
  hosts: agent
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker-ce

    - name: Install Docker engine
      apt:
        name: docker-ce
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups: docker
      notify: restart docker

    - name: Disable Docker root access via TCP
      lineinfile:
        path: /etc/default/docker
        regexp: "^DOCKER_OPTS"
        line: 'DOCKER_OPTS="-H unix:///var/run/docker.sock"'
        state: present
      notify: restart docker

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=', line: 'Server=zabbix-server.example.com' }
        - { regexp: '^ServerActive=', line: 'ServerActive=zabbix-server.example.com' }
        - { regexp: '^Hostname=', line: 'Hostname={{ ansible_hostname }}' }

  handlers:
    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
    - name: restart zabbix agent
      systemd:
        name: zabbix-agent.service
        state: restarted

